services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"     # MQTT протокол (TCP)
      - "9001:9001"     # WebSocket (необов'язково)
    volumes:
      - ./broker/mosquitto/config:/mosquitto/config
      - ./broker/mosquitto/data:/mosquitto/data
      - ./broker/mosquitto/log:/mosquitto/log
    restart: unless-stopped