# generated by datamodel-codegen:
#   filename:  shared-spec.yaml
#   timestamp: 2025-06-24T15:16:49+00:00

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel


class Account(BaseModel):
    id: UUID


class ErrorBase(BaseModel):
    message: str


class ErrorResponse(BaseModel):
    errors: list[ErrorBase]
