# generated by datamodel-codegen:
#   filename:  user-spec.yaml
#   timestamp: 2025-06-24T14:52:09+00:00

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, EmailStr, Field, SecretStr


class UserBase(BaseModel):
    username: str = Field(..., max_length=50, min_length=3)
    email: EmailStr


class UserRegistrationRequest(UserBase):
    password: SecretStr = Field(..., min_length=8)


class CreateUserRequest(UserBase):
    accountId: UUID


class UserResponse(UserBase):
    id: UUID
