openapi: 3.1.0
info:
  title: Tasks management
  description: Api for tasks management
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /v1/flats:
    get:
      tags:
        - Tag
      summary: gets all list of tasks
      responses:
        '200':
          description: successful operation


components:
  schemas:
    Room:
      type: object
      properties:

    Flat:
      type: object
      properties:
        rooms:
          type:
            - array
