openapi: 3.1.0
info:
  title: Tasks management
  description: Api for tasks management
  version: 1.0.0

components:
  schemas:
    Account:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          format: uuid

    ErrorResponse:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorBase'

    ErrorBase:
      type: object
      required:
        - message
      properties:
        message:
          type: string
