openapi: 3.0.3
info:
  title: User Management API
  description: API for user registration and management
  version: 1.0.0

paths:
  /api/users/register:
    post:
      summary: Register a new user in new Account
      operationId: registerUser
      tags:
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistrationRequest'
      responses:
        '201':
          description: User successfully registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '409':
          description: Username already exists
          content:
            application/json:
              schema:
                $ref: './shared-spec.yaml#/components/schemas/ErrorResponse'
        '422':
          description: Unprocessable user request
          content:
            application/json:
              schema:
                $ref: './shared-spec.yaml#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: './shared-spec.yaml#/components/schemas/ErrorResponse'

  /api/users:
    post:
      security:
        - bearerAuth: [ ]
      summary: Create a new user in Account
      operationId: createUser
      tags:
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        '201':
          description: User successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '401':
          description: Unauthenticated
          content:
            application/json:
              schema:
                $ref: './shared-spec.yaml#/components/schemas/ErrorResponse'
        '403':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: './shared-spec.yaml#/components/schemas/ErrorResponse'
        '409':
          description: Username already exists
          content:
            application/json:
              schema:
                $ref: './shared-spec.yaml#/components/schemas/ErrorResponse'
        '422':
          description: Unprocessable user request
          content:
            application/json:
              schema:
                $ref: './shared-spec.yaml#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: './shared-spec.yaml#/components/schemas/ErrorResponse'

    get:
      security:
        - bearerAuth: [ ]
      summary: Get all users for account
      operationId: getUsers
      tags:
        - users
      parameters:
        - name: page
          in: query
          description: Page number for pagination
          required: false
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          description: Number of items per page
          required: false
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: List of users retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserResponse'
        '401':
          description: Unauthenticated
          content:
            application/json:
              schema:
                $ref: './shared-spec.yaml#/components/schemas/ErrorResponse'
        '403':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: './shared-spec.yaml#/components/schemas/ErrorResponse'

  /api/users/me:
    get:
      security:
        - bearerAuth: [ ]
      summary: Get logged user
      operationId: getLoggedUser
      tags:
        - users
      responses:
        '201':
          description: User successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '401':
          description: Unauthenticated
          content:
            application/json:
              schema:
                $ref: './shared-spec.yaml#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    UserRegistrationRequest:
      allOf:
        - $ref: '#/components/schemas/UserBase'
        - type: object
          required:
            - password
          properties:
            password:
              type: string
              minLength: 8
              format: password

    CreateUserRequest:
      allOf:
        - $ref: '#/components/schemas/UserBase'
        - type: object
          required:
            - accountId
          properties:
            accountId:
              type: string
              format: uuid

    UserResponse:
      allOf:
        - $ref: '#/components/schemas/UserBase'
        - type: object
          required:
            - id
          properties:
              id:
                type: string
                format: uuid

    UserBase:
      type: object
      required:
        - username
        - email
      properties:
        username:
          type: string
          minLength: 3
          maxLength: 50
        email:
          type: string
          format: email
